### ISSUE TITLE
OpenCV_FOUND to FALSE 

### ISSUE THREAD

**Issue by mahna3411** [ValYouW/AndroidOpenCVDemo#1]
Found package configuration file:
    C:/tools/OpenCV-android-sdk/sdk/native/jni/OpenCVConfig.cmake
  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
  NOT FOUND.

I get this error, how can I fix it?
opencv Version 4.5
android Studio Version 4.1

**Comment by ValYouW** [comment]
I dont know... I tested with OpenCV 4.2.0 and it seems to be working fine.
You can try and carefully go over the "Configure OpenCV build" in [this](https://www.thecodingnotebook.com/2020/04/image-processing-with-opencv-in-android.html) post.

**Comment by mahna3411** [comment]
That's right, I got the answer with the same link and it was solved.
